spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hll_workflow_test?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: root
    password: root
